/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GoalVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createGoal"
      | "deposit"
      | "getOwnerGoals"
      | "getProgress"
      | "goals"
      | "goalsByOwner"
      | "nextGoalId"
      | "withdrawWhenCompleted"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Deposited" | "GoalCreated" | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createGoal",
    values: [string, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerGoals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProgress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "goals", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "goalsByOwner",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextGoalId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawWhenCompleted",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "createGoal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerGoals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "goals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "goalsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextGoalId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawWhenCompleted",
    data: BytesLike
  ): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    goalId: BigNumberish,
    from: AddressLike,
    amount: BigNumberish,
    savedAmount: BigNumberish
  ];
  export type OutputTuple = [
    goalId: bigint,
    from: string,
    amount: bigint,
    savedAmount: bigint
  ];
  export interface OutputObject {
    goalId: bigint;
    from: string;
    amount: bigint;
    savedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GoalCreatedEvent {
  export type InputTuple = [
    goalId: BigNumberish,
    owner: AddressLike,
    name: string,
    token: AddressLike,
    targetAmount: BigNumberish
  ];
  export type OutputTuple = [
    goalId: bigint,
    owner: string,
    name: string,
    token: string,
    targetAmount: bigint
  ];
  export interface OutputObject {
    goalId: bigint;
    owner: string;
    name: string;
    token: string;
    targetAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    goalId: BigNumberish,
    owner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [goalId: bigint, owner: string, amount: bigint];
  export interface OutputObject {
    goalId: bigint;
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GoalVault extends BaseContract {
  connect(runner?: ContractRunner | null): GoalVault;
  waitForDeployment(): Promise<this>;

  interface: GoalVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createGoal: TypedContractMethod<
    [name: string, targetAmount: BigNumberish, token: AddressLike],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [goalId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getOwnerGoals: TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;

  getProgress: TypedContractMethod<[goalId: BigNumberish], [bigint], "view">;

  goals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean] & {
        owner: string;
        name: string;
        token: string;
        targetAmount: bigint;
        savedAmount: bigint;
        completed: boolean;
      }
    ],
    "view"
  >;

  goalsByOwner: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  nextGoalId: TypedContractMethod<[], [bigint], "view">;

  withdrawWhenCompleted: TypedContractMethod<
    [goalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createGoal"
  ): TypedContractMethod<
    [name: string, targetAmount: BigNumberish, token: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [goalId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOwnerGoals"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getProgress"
  ): TypedContractMethod<[goalId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "goals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean] & {
        owner: string;
        name: string;
        token: string;
        targetAmount: bigint;
        savedAmount: bigint;
        completed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "goalsByOwner"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextGoalId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawWhenCompleted"
  ): TypedContractMethod<[goalId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "GoalCreated"
  ): TypedContractEvent<
    GoalCreatedEvent.InputTuple,
    GoalCreatedEvent.OutputTuple,
    GoalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(uint256,address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "GoalCreated(uint256,address,string,address,uint256)": TypedContractEvent<
      GoalCreatedEvent.InputTuple,
      GoalCreatedEvent.OutputTuple,
      GoalCreatedEvent.OutputObject
    >;
    GoalCreated: TypedContractEvent<
      GoalCreatedEvent.InputTuple,
      GoalCreatedEvent.OutputTuple,
      GoalCreatedEvent.OutputObject
    >;

    "Withdrawn(uint256,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
