/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GoalManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelSchedule"
      | "createSchedule"
      | "pauseSchedule"
      | "resumeSchedule"
      | "scheduleIds"
      | "schedules"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ScheduleCanceled"
      | "ScheduleCreated"
      | "SchedulePaused"
      | "ScheduleResumed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelSchedule",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createSchedule",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pauseSchedule",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resumeSchedule",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "schedules",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pauseSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resumeSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "schedules", data: BytesLike): Result;
}

export namespace ScheduleCanceledEvent {
  export type InputTuple = [scheduleId: BytesLike];
  export type OutputTuple = [scheduleId: string];
  export interface OutputObject {
    scheduleId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleCreatedEvent {
  export type InputTuple = [
    scheduleId: BytesLike,
    owner: AddressLike,
    goalId: BigNumberish,
    amount: BigNumberish,
    cadenceSeconds: BigNumberish,
    nextRunAt: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: string,
    owner: string,
    goalId: bigint,
    amount: bigint,
    cadenceSeconds: bigint,
    nextRunAt: bigint
  ];
  export interface OutputObject {
    scheduleId: string;
    owner: string;
    goalId: bigint;
    amount: bigint;
    cadenceSeconds: bigint;
    nextRunAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SchedulePausedEvent {
  export type InputTuple = [scheduleId: BytesLike];
  export type OutputTuple = [scheduleId: string];
  export interface OutputObject {
    scheduleId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleResumedEvent {
  export type InputTuple = [scheduleId: BytesLike];
  export type OutputTuple = [scheduleId: string];
  export interface OutputObject {
    scheduleId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GoalManager extends BaseContract {
  connect(runner?: ContractRunner | null): GoalManager;
  waitForDeployment(): Promise<this>;

  interface: GoalManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelSchedule: TypedContractMethod<
    [scheduleId: BytesLike],
    [void],
    "nonpayable"
  >;

  createSchedule: TypedContractMethod<
    [goalId: BigNumberish, amount: BigNumberish, cadenceSeconds: BigNumberish],
    [string],
    "nonpayable"
  >;

  pauseSchedule: TypedContractMethod<
    [scheduleId: BytesLike],
    [void],
    "nonpayable"
  >;

  resumeSchedule: TypedContractMethod<
    [scheduleId: BytesLike],
    [void],
    "nonpayable"
  >;

  scheduleIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  schedules: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        owner: string;
        goalId: bigint;
        amount: bigint;
        cadenceSeconds: bigint;
        nextRunAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelSchedule"
  ): TypedContractMethod<[scheduleId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createSchedule"
  ): TypedContractMethod<
    [goalId: BigNumberish, amount: BigNumberish, cadenceSeconds: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pauseSchedule"
  ): TypedContractMethod<[scheduleId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resumeSchedule"
  ): TypedContractMethod<[scheduleId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scheduleIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "schedules"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        owner: string;
        goalId: bigint;
        amount: bigint;
        cadenceSeconds: bigint;
        nextRunAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ScheduleCanceled"
  ): TypedContractEvent<
    ScheduleCanceledEvent.InputTuple,
    ScheduleCanceledEvent.OutputTuple,
    ScheduleCanceledEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleCreated"
  ): TypedContractEvent<
    ScheduleCreatedEvent.InputTuple,
    ScheduleCreatedEvent.OutputTuple,
    ScheduleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SchedulePaused"
  ): TypedContractEvent<
    SchedulePausedEvent.InputTuple,
    SchedulePausedEvent.OutputTuple,
    SchedulePausedEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleResumed"
  ): TypedContractEvent<
    ScheduleResumedEvent.InputTuple,
    ScheduleResumedEvent.OutputTuple,
    ScheduleResumedEvent.OutputObject
  >;

  filters: {
    "ScheduleCanceled(bytes32)": TypedContractEvent<
      ScheduleCanceledEvent.InputTuple,
      ScheduleCanceledEvent.OutputTuple,
      ScheduleCanceledEvent.OutputObject
    >;
    ScheduleCanceled: TypedContractEvent<
      ScheduleCanceledEvent.InputTuple,
      ScheduleCanceledEvent.OutputTuple,
      ScheduleCanceledEvent.OutputObject
    >;

    "ScheduleCreated(bytes32,address,uint256,uint256,uint64,uint64)": TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;
    ScheduleCreated: TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;

    "SchedulePaused(bytes32)": TypedContractEvent<
      SchedulePausedEvent.InputTuple,
      SchedulePausedEvent.OutputTuple,
      SchedulePausedEvent.OutputObject
    >;
    SchedulePaused: TypedContractEvent<
      SchedulePausedEvent.InputTuple,
      SchedulePausedEvent.OutputTuple,
      SchedulePausedEvent.OutputObject
    >;

    "ScheduleResumed(bytes32)": TypedContractEvent<
      ScheduleResumedEvent.InputTuple,
      ScheduleResumedEvent.OutputTuple,
      ScheduleResumedEvent.OutputObject
    >;
    ScheduleResumed: TypedContractEvent<
      ScheduleResumedEvent.InputTuple,
      ScheduleResumedEvent.OutputTuple,
      ScheduleResumedEvent.OutputObject
    >;
  };
}
