/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as goalVaultSol from "./GoalVault.sol";
export type { goalVaultSol };
export type { GoalManager } from "./GoalManager";
export type { RitualIdentityRegistry } from "./RitualIdentityRegistry";
export * as factories from "./factories";
export { GoalManager__factory } from "./factories/GoalManager__factory";
export type { GoalVault } from "./GoalVault.sol/GoalVault";
export { GoalVault__factory } from "./factories/GoalVault.sol/GoalVault__factory";
export type { IERC20 } from "./GoalVault.sol/IERC20";
export { IERC20__factory } from "./factories/GoalVault.sol/IERC20__factory";
export { RitualIdentityRegistry__factory } from "./factories/RitualIdentityRegistry__factory";
