/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RitualIdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimUsername"
      | "identityOf"
      | "isAvailable"
      | "ownerOfUsername"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "UsernameClaimed"): EventFragment;

  encodeFunctionData(
    functionFragment: "claimUsername",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "identityOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isAvailable", values: [string]): string;
  encodeFunctionData(
    functionFragment: "ownerOfUsername",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "identityOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerOfUsername",
    data: BytesLike
  ): Result;
}

export namespace UsernameClaimedEvent {
  export type InputTuple = [
    owner: AddressLike,
    username: string,
    memberSince: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    username: string,
    memberSince: bigint
  ];
  export interface OutputObject {
    owner: string;
    username: string;
    memberSince: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RitualIdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): RitualIdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: RitualIdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimUsername: TypedContractMethod<[username: string], [void], "nonpayable">;

  identityOf: TypedContractMethod<
    [arg0: AddressLike],
    [[string, bigint] & { username: string; memberSince: bigint }],
    "view"
  >;

  isAvailable: TypedContractMethod<[username: string], [boolean], "view">;

  ownerOfUsername: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimUsername"
  ): TypedContractMethod<[username: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "identityOf"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[string, bigint] & { username: string; memberSince: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAvailable"
  ): TypedContractMethod<[username: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "ownerOfUsername"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getEvent(
    key: "UsernameClaimed"
  ): TypedContractEvent<
    UsernameClaimedEvent.InputTuple,
    UsernameClaimedEvent.OutputTuple,
    UsernameClaimedEvent.OutputObject
  >;

  filters: {
    "UsernameClaimed(address,string,uint64)": TypedContractEvent<
      UsernameClaimedEvent.InputTuple,
      UsernameClaimedEvent.OutputTuple,
      UsernameClaimedEvent.OutputObject
    >;
    UsernameClaimed: TypedContractEvent<
      UsernameClaimedEvent.InputTuple,
      UsernameClaimedEvent.OutputTuple,
      UsernameClaimedEvent.OutputObject
    >;
  };
}
